version: '3'

services:
  database:
    image: mongo:latest
    container_name: nds-mongo
    environment:
      MONGO_INITDB_DATABASE: #DB_NAME
      MONGO_INITDB_ROOT_USERNAME: #DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: #DB_PASSWORD
    ports:
    - 27017:27017

    volumes:
    - ./mongo-volume:/data/db

    restart: always

volumes:
  mongo-volume:
